In [32]:
# 1
import numpy as np
n = np.arange(1, 11)
m = np.linspace(1, 10, num=10, dtype=int)
print(m, n, sep='\n')

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [33]:
# 2
m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [3]:
# 3
b = np.random.randint(1, 10, (5, 5), dtype=int)
print(b)

[[8 7 5 3 1]
 [6 6 9 7 1]
 [4 1 7 7 1]
 [3 2 6 1 6]
 [4 8 2 6 9]]


In [4]:
# 4
b = np.random.random((4, 4))
print(b)

[[0.55051049 0.82682821 0.3916079  0.00153981]
 [0.11024193 0.48982255 0.09686976 0.02966943]
 [0.24466797 0.21439817 0.0971667  0.91538595]
 [0.58626609 0.13213075 0.9668377  0.89043047]]


In [34]:
# 5
a = np.random.randint(1, 10, 5, dtype=int)
b = np.random.randint(1, 10, 5, dtype=int)
print(f"Array a: {a}\nArray b: {b}")
print(f"Sum of arrays: {a + b}, \nDifference of arrays: {a - b}, \nProduct of arrays: {a * b}", sep='\n')

Array a: [1 8 5 9 8]
Array b: [5 9 6 2 8]
Sum of arrays: [ 6 17 11 11 16], 
Difference of arrays: [-4 -1 -1  7  0], 
Product of arrays: [ 5 72 30 18 64]


In [6]:
# 6
a = np.random.random(7)
b = np.random.random(7)
print(f"Array a: {a}\nArray b: {b}")
print(f"Scalar product: {np.dot(a, b)}")

Array a: [0.85825095 0.86302971 0.33101373 0.02572712 0.80620612 0.14681086
 0.43592753]
Array b: [0.00493116 0.39756326 0.12267948 0.17822827 0.90530446 0.61472913
 0.90437121]
Scalar product: 1.606886193067702


In [30]:
#7
a = np.random.randint(1, 10, (2, 2), dtype=int)
b = np.random.randint(1, 10, (2, 3), dtype=int)
print(f"Matrix a: \n{a}\nMatrix b: \n{b}")
print(f"\nMultiply matrices: \n{np.dot(a, b)}")

Matrix a: 
[[3 6]
 [7 4]]
Matrix b: 
[[7 6 6]
 [6 4 3]]

Multiply matrices: 
[[57 42 36]
 [73 58 54]]


In [29]:
# 8
a = np.random.randint(1, 10, (3, 3), dtype=int)
print(f'Matrix a: \n{a}')
print(f'Inverse matrix: \n{np.linalg.inv(a)}')

Matrix a: 
[[1 2 6]
 [8 2 7]
 [8 1 8]]
Inverse matrix: 
[[-0.16363636  0.18181818 -0.03636364]
 [ 0.14545455  0.72727273 -0.74545455]
 [ 0.14545455 -0.27272727  0.25454545]]


In [15]:
# 9
a = np.random.random((4, 4))
print(f'Matrix a: \n{a}')
print(f'Transposed matrix: \n{a.T}')

Matrix a: 
[[0.90354855 0.04088244 0.66444907 0.28195561]
 [0.37075296 0.16179149 0.85789697 0.92168976]
 [0.13175383 0.23515772 0.56424899 0.49767591]
 [0.5096188  0.16770892 0.65617519 0.63727963]]
Transposed matrix: 
[[0.90354855 0.37075296 0.13175383 0.5096188 ]
 [0.04088244 0.16179149 0.23515772 0.16770892]
 [0.66444907 0.85789697 0.56424899 0.65617519]
 [0.28195561 0.92168976 0.49767591 0.63727963]]


In [28]:
# 10
a = np.random.randint(1, 10, (3, 4), dtype=int)
b = np.random.randint(1, 10, 4, dtype=int)
print(f"Matrix: \n{a}, \nVector: {b}")
print(f"\nMultiply matrix and vector: \n{np.dot(a, b)}")

Matrix: 
[[3 5 5 8]
 [5 2 9 5]
 [8 7 1 8]], 
Vector: [1 3 8 1]

Multiply matrix and vector: 
[66 88 45]


In [27]:
# 11
a = np.random.random((2, 3))
b = np.random.random(3)
print(f"Matrix: \n{a}, \nVector: {b}")
print(f"\nMultiply matrix and vector: \n{a @ b}")

Matrix: 
[[0.01169193 0.12408384 0.17929572]
 [0.28395732 0.1401576  0.04710548]], 
Vector: [0.6685972  0.07651884 0.10176914]

Multiply matrix and vector: 
[0.03555872 0.20537165]


In [25]:
# 12
a = np.random.randint(1, 10, (2, 2), dtype=int)
b = np.random.randint(1, 10, (2, 2), dtype=int)
print(f"Matrix a: \n{a}, \nMatrix b: \n{b}")
print(f"\nElementwise product: \n{a * b}")

Matrix a: 
[[6 7]
 [4 3]], 
Matrix b: 
[[1 4]
 [7 9]]

Elementwise product: 
[[ 6 28]
 [28 27]]


In [23]:
# 13
m = np.random.randint(1, 10, (2, 2), dtype=int)
n = np.random.randint(1, 10, (2, 2), dtype=int)
print(f"Matrix m: \n{m}, \nMatrix n: \n{n}")
print(f"\nMultiply matrices: \n{np.dot(m, n)}")

Matrix m: 
[[1 1]
 [5 3]], 
Matrix n: 
[[8 6]
 [8 8]]

Multiply matrices: 
[[16 14]
 [64 54]]


In [36]:
# 14
m = np.random.randint(1, 100, (5, 5), dtype=int)

print(f"Matrix m: \n{m}")
print(f"\nSum of elements: \n{m.sum()}")

Matrix m: 
[[ 7 41 76  4 28]
 [79 97 81 28  5]
 [10 66 18 63  8]
 [52 93 20  9 70]
 [15 48 69 90 90]]

Sum of elements: 
1167


In [37]:
# 15
m = np.random.randint(1, 10, (4, 4), dtype=int)
n = np.random.randint(1, 10, (4, 4), dtype=int)
print(f"Matrix m: \n{m}, \nMatrix n: \n{n}")
print(f"\nMatrix difference: \n{m - n}")

Matrix m: 
[[6 5 7 9]
 [1 9 2 4]
 [6 4 1 3]
 [6 7 7 1]], 
Matrix n: 
[[4 1 9 4]
 [3 5 5 7]
 [1 7 3 4]
 [7 2 9 3]]

Matrix difference: 
[[ 2  4 -2  5]
 [-2  4 -3 -3]
 [ 5 -3 -2 -1]
 [-1  5 -2 -2]]


In [39]:
# 16
m = np.random.random((3, 3))

print(f"Matrix m: \n{m}")
first = m[0, 0] + m[0, 1] + m[0, 2]
second = m[1, 0] + m[1, 1] + m[1, 2]
third = m[2, 0] + m[2, 1] + m[2, 2]

vector = np.array([first, second, third])
same_vector = m.sum(axis=1).reshape(-1, 1)

print(f"Vector: \n{vector}")
print(f"Same_Vector: \n{same_vector}")

Matrix m: 
[[0.59656826 0.21316929 0.70254474]
 [0.08499623 0.48683667 0.4895406 ]
 [0.87168117 0.50089817 0.0680747 ]]
Vector: 
[1.51228229 1.0613735  1.44065403]
Same_Vector: 
[[1.51228229]
 [1.0613735 ]
 [1.44065403]]


In [40]:
# 17
m = np.random.randint(1, 10, (3, 4))
squared_matrix = m ** 2

print(f"Matrix m:\n{m}")
print(f"\nSquared matrix:\n{squared_matrix}")

Matrix m:
[[8 7 3 9]
 [2 3 6 8]
 [8 9 3 1]]

Squared matrix:
[[64 49  9 81]
 [ 4  9 36 64]
 [64 81  9  1]]


In [41]:
# 18
m = np.random.randint(1, 50, 4)
new_vector = m ** 0.5

print(f"Vector m:\n{m}")
print(f"\nVector with square roots:\n{new_vector}")

Vector m:
[36  4 11 48]

Vector with square roots:
[6.         2.         3.31662479 6.92820323]
