In [1]:
# 1
import numpy as np
n = np.arange(1, 11)
m = np.linspace(1, 10, num=10)
print(m, n, sep='\n')

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
# 2
m = np.zeros((3, 3))
print(m)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# 3
b = np.random.randint(1, 10, (5, 5))
print(b)

[[8 7 5 3 1]
 [6 6 9 7 1]
 [4 1 7 7 1]
 [3 2 6 1 6]
 [4 8 2 6 9]]


In [4]:
# 4
b = np.random.random((4, 4))
print(b)

[[0.55051049 0.82682821 0.3916079  0.00153981]
 [0.11024193 0.48982255 0.09686976 0.02966943]
 [0.24466797 0.21439817 0.0971667  0.91538595]
 [0.58626609 0.13213075 0.9668377  0.89043047]]


In [5]:
# 5
a = np.random.randint(1, 10, 5)
b = np.random.randint(1, 10, 5)
print(f"Array a: {a}\nArray b: {b}")
print(f"Sum of arrays: {a + b}, \nDifference of arrays: {a - b}, \nProduct of arrays: {a * b}", sep='\n')

Array a: [8 8 1 3 9]
Array b: [3 5 3 4 4]
Sum of arrays: [11 13  4  7 13], 
Difference of arrays: [ 5  3 -2 -1  5], 
Product of arrays: [24 40  3 12 36]


In [6]:
# 6
a = np.random.random(7)
b = np.random.random(7)
print(f"Array a: {a}\nArray b: {b}")
print(f"Scalar product: {np.dot(a, b)}")

Array a: [0.85825095 0.86302971 0.33101373 0.02572712 0.80620612 0.14681086
 0.43592753]
Array b: [0.00493116 0.39756326 0.12267948 0.17822827 0.90530446 0.61472913
 0.90437121]
Scalar product: 1.606886193067702


In [7]:
#7
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 3))
print(f"Matrix a: \n{a}\nMatrix b: \n{b}")
print(f"\nMultiply matrices: \n{np.dot(a, b)}")

Matrix a: 
[[4 5]
 [5 7]]
Matrix b: 
[[9 2 3]
 [5 4 9]]

Multiply matrices: 
[[61 28 57]
 [80 38 78]]


In [14]:
# 8
a = np.random.randint(1, 10, (3, 3))
print(f'Matrix a: \n{a}')
print(f'Inverse matrix: \n{np.linalg.inv(a)}')

Matrix a: 
[[9 9 1]
 [2 3 9]
 [2 8 5]]
Inverse matrix: 
[[ 0.13225058  0.08584687 -0.18097448]
 [-0.01856148 -0.09976798  0.18329466]
 [-0.02320186  0.12529002 -0.02088167]]


In [15]:
# 9
a = np.random.random((4, 4))
print(f'Matrix a: \n{a}')
print(f'Transposed matrix: \n{a.T}')

Matrix a: 
[[0.90354855 0.04088244 0.66444907 0.28195561]
 [0.37075296 0.16179149 0.85789697 0.92168976]
 [0.13175383 0.23515772 0.56424899 0.49767591]
 [0.5096188  0.16770892 0.65617519 0.63727963]]
Transposed matrix: 
[[0.90354855 0.37075296 0.13175383 0.5096188 ]
 [0.04088244 0.16179149 0.23515772 0.16770892]
 [0.66444907 0.85789697 0.56424899 0.65617519]
 [0.28195561 0.92168976 0.49767591 0.63727963]]


In [ ]:
# 10
